## Read in the data from the Wiki using pandas

In [7]:
import pandas as pd

df=pd.read_html("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
df=df[0]
df.head(10)

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M5A  Downtown Toronto       Regent Park
6      M6A        North York  Lawrence Heights
7      M6A        North York    Lawrence Manor
8      M7A      Queen's Park      Not assigned
9      M8A      Not assigned      Not assigned

### Get rid of the cell with "Not assigend" for Borough column

In [8]:
# Ignore cells with a borough that is Not assigned. 
df = df[df['Borough']!='Not assigned'].reset_index(drop=True)
df.head(10)

  Postcode           Borough     Neighbourhood
0      M3A        North York         Parkwoods
1      M4A        North York  Victoria Village
2      M5A  Downtown Toronto      Harbourfront
3      M5A  Downtown Toronto       Regent Park
4      M6A        North York  Lawrence Heights
5      M6A        North York    Lawrence Manor
6      M7A      Queen's Park      Not assigned
7      M9A         Etobicoke  Islington Avenue
8      M1B       Scarborough             Rouge
9      M1B       Scarborough           Malvern

### Loop the unique list to repalce the Neighbourhood value

In [9]:
# combined different neighbourhood under the same boroough to the same row 
temp_list=df['Postcode'].unique().tolist() # Generate the unique list of the postcode
for i in temp_list:
    temp_count = df[df['Postcode']==i].shape[0] # Count how many records each postcode has
    if temp_count>1:
        index_list=df[df['Postcode']==i].index.tolist() # Get the index of these records wiith more than 1 record
        # Get all the unique nieghbourhood for each borough and then assign them to each borough
        df.loc[index_list,'Neighbourhood']=' ,'.join(df[df['Postcode']==i]['Neighbourhood'].unique().tolist())
        
df.head(10)

  Postcode           Borough                     Neighbourhood
0      M3A        North York                         Parkwoods
1      M4A        North York                  Victoria Village
2      M5A  Downtown Toronto         Harbourfront ,Regent Park
3      M5A  Downtown Toronto         Harbourfront ,Regent Park
4      M6A        North York  Lawrence Heights ,Lawrence Manor
5      M6A        North York  Lawrence Heights ,Lawrence Manor
6      M7A      Queen's Park                      Not assigned
7      M9A         Etobicoke                  Islington Avenue
8      M1B       Scarborough                    Rouge ,Malvern
9      M1B       Scarborough                    Rouge ,Malvern

### Allign the Neighbourhood value with borough

In [17]:
# If Neighbourhood is not assigned, then Neighourhood = borough

replace_list=df[df['Neighbourhood'] == "Not assigned"].index.tolist() # Find out the index for these Not assigned Neighbourhood
for index in replace_list:
    df.loc[index,'Neighbourhood']=df.loc[index,'Borough'] #for each index, use the Borough value to replae the "Not assigned"
    
df.head(10)

### The number of rows of the final dataframe

In [20]:
df.shape[0]

211